"""Em-Cubed: Neuro-Symbolic Ontological Framework & Polyglot Skill Engine.

Enforces formal semantic truth at the ledger level ("Pydantic at the door, Ontology at the ledger")
and leverages multi-surface reasoning coprocessors (Python, Prolog, Z3, Datalog, Hy, SQLite).
"""

from .indexer import reindex, get_skill_metadata  # noqa: E402
from .search import search_registry  # noqa: E402
from .surfaces import PrologSurface, HySurface, PythonSurface, Z3Surface, DatalogSurface, JanusSurface, SQLiteSurface, QuickJSSurface  # noqa: E402
from .skills import (
    SkillMetadata,
    SkillValidator,
    ValidationResult,
    SkillRegistry,
    QualityMetrics,
    SkillComposer,
    CompositionResult,
    SkillBenchmark,
    BenchmarkResult,
    SkillRecommender,
    RecommendationResult,
    SkillQualityPipeline,
    TelemetryCollector,
    ExecutionRecord,
    SkillTelemetry,
    SkillExecutor,
    initialize_telemetry,
    initialize_executor,
)

__version__ = "0.7.0"  # Added SQLite session persistence, QuickJS context fix, Cangjie stdin pipe, Jinja2 templates, new CLI commands, ADR 004/005
__all__ = [
    "reindex",
    "get_skill_metadata",
    "search_registry",
    "PythonSurface",
    "PrologSurface",
    "HySurface",
    "Z3Surface",
    "DatalogSurface",
    "JanusSurface",
    "SQLiteSurface",
    "QuickJSSurface",
    # Skills quality framework
    "SkillMetadata",
    "SkillValidator",
    "ValidationResult",
    "SkillRegistry",
    "QualityMetrics",
    "SkillComposer",
    "CompositionResult",
    "SkillBenchmark",
    "BenchmarkResult",
    "SkillRecommender",
    "RecommendationResult",
    "SkillQualityPipeline",
    "TelemetryCollector",
    "ExecutionRecord",
    "SkillTelemetry",
    "SkillExecutor",
    "initialize_telemetry",
    "initialize_executor",
    # Loopy & Ontology Framework
    "BaseLoopySkill",
    "LoopySkillRunner",
    "TextLoopMiner",
    "OntologyLedgerValidator",
    "OntologyTriple",
    "GraphPathRAG",
    "ConstraintSteeringCompiler",
    "TrajectoryAuditor",
    "TruthValue",
    "SubobjectClassifier",
    "SurfaceMorphism",
    "SkillEvolutionEngine",
    "TripleInductionEngine",
    "MultiAgentToposConsensus",
    "FederatedOntologyRegistry",
    "KnowledgeGraphVisualizer",
    "KnowledgeElicitationPipeline",
    "DecisionSupportQuestion",
    "CompetencyQuestion",
    "PMESTFacets",
    "OntoCleanPartition",
    "EntityType",
    "ExactTruthmaker",
    "ExactTruthmakerClassifier",
    "HyperintensionalEvaluator",
    "StateFragment",
]

from em_cubed.loopy import (  # noqa: E402
    BaseLoopySkill,
    LoopySkillRunner,
    SkillEvolutionEngine,
    TextLoopMiner,
    TrajectoryAuditor,
)
from em_cubed.ontology import (  # noqa: E402
    CompetencyQuestion,
    ConstraintSteeringCompiler,
    DecisionSupportQuestion,
    EntityType,
    ExactTruthmaker,
    ExactTruthmakerClassifier,
    FederatedOntologyRegistry,
    GraphPathRAG,
    HyperintensionalEvaluator,
    KnowledgeElicitationPipeline,
    KnowledgeGraphVisualizer,
    MultiAgentToposConsensus,
    OntoCleanPartition,
    OntologyLedgerValidator,
    OntologyTriple,
    PMESTFacets,
    StateFragment,
    SubobjectClassifier,
    TripleInductionEngine,
    TruthValue,
)
from em_cubed.surfaces import SurfaceMorphism  # noqa: E402
