"""Em-Cubed: Neuro-Symbolic Ontological Framework & Polyglot Skill Engine.

Enforces formal semantic truth at the ledger level ("Pydantic at the door, Ontology at the ledger")
and leverages multi-surface reasoning coprocessors (Python, Prolog, Z3, Datalog, Hy, SQLite).
"""

from .indexer import get_skill_metadata, reindex  # noqa: E402
from .search import search_registry  # noqa: E402
from .skills import (  # noqa: E402
    BenchmarkResult,
    CompositionResult,
    ExecutionRecord,
    QualityMetrics,
    RecommendationResult,
    SkillBenchmark,
    SkillComposer,
    SkillExecutor,
    SkillMetadata,
    SkillQualityPipeline,
    SkillRecommender,
    SkillRegistry,
    SkillTelemetry,
    SkillValidator,
    TelemetryCollector,
    ValidationResult,
    initialize_executor,
    initialize_telemetry,
)
from .surfaces import (  # noqa: E402
    DatalogSurface,
    HySurface,
    JanusSurface,
    PrologSurface,
    PythonSurface,
    QuickJSSurface,
    SQLiteSurface,
    Z3Surface,
)

__version__ = "0.8.0"
__all__ = [
    "reindex",
    "get_skill_metadata",
    "search_registry",
    "PythonSurface",
    "PrologSurface",
    "HySurface",
    "Z3Surface",
    "DatalogSurface",
    "JanusSurface",
    "SQLiteSurface",
    "QuickJSSurface",
    # Skills quality framework
    "SkillMetadata",
    "SkillValidator",
    "ValidationResult",
    "SkillRegistry",
    "QualityMetrics",
    "SkillComposer",
    "CompositionResult",
    "SkillBenchmark",
    "BenchmarkResult",
    "SkillRecommender",
    "RecommendationResult",
    "SkillQualityPipeline",
    "TelemetryCollector",
    "ExecutionRecord",
    "SkillTelemetry",
    "SkillExecutor",
    "initialize_telemetry",
    "initialize_executor",
    # Loopy & Ontology Framework
    "BaseLoopySkill",
    "LoopySkillRunner",
    "TextLoopMiner",
    "OntologyLedgerValidator",
    "OntologyTriple",
    "GraphPathRAG",
    "ConstraintSteeringCompiler",
    "TrajectoryAuditor",
    "TruthValue",
    "SubobjectClassifier",
    "SurfaceMorphism",
    "SkillEvolutionEngine",
    "TripleInductionEngine",
    "MultiAgentToposConsensus",
    "FederatedOntologyRegistry",
    "KnowledgeGraphVisualizer",
    "KnowledgeElicitationPipeline",
    "DecisionSupportQuestion",
    "CompetencyQuestion",
    "PMESTFacets",
    "OntoCleanPartition",
    "EntityType",
    "ExactTruthmaker",
    "ExactTruthmakerClassifier",
    "HyperintensionalEvaluator",
    "StateFragment",
    "DescriptionLogicExpression",
    "ConceptInductionEngine",
    "NeuronConceptAligner",
    "ReducerType",
    "DerivedPropertyReducer",
    "OntologyInterface",
    "InterfaceImplementation",
    "ObjectBacklinkRegistry",
    "SchemaVersion",
    "SchemaMigrationStep",
    "ForwardBackwardCompatibilityChecker",
    "AutomatedTripleMigrationEngine",
    "OntologySchemaMigrator",
    "OntologyHealthReport",
    "OntologicalHealthMonitor",
    "SelfHealingGuardrailEngine",
    "TimeInterval",
    "GeoLocation",
    "TemporalSpatialTriple",
    "WorldStateTimeline",
    "TemporalSnapshotQueryEngine",
    "SpatialProximityReasoner",
    "RDFSerializer",
    "SHACLConstraintGenerator",
    "OWLImporter",
    "SwarmRunConfig",
    "SwarmExecutionReport",
    "DualEngineSwarmOrchestrator",
    "EventType",
    "StreamEvent",
    "ReactiveRule",
    "StreamProcessingResult",
    "OntologyEventStreamProcessor",
    "OntologyTUIDashboard",
    "run_cli_tui_mode",
    "SurfaceFunctor",
    "OntologyMonad",
]

from em_cubed.cli_tui import OntologyTUIDashboard, run_cli_tui_mode  # noqa: E402

from em_cubed.loopy import (  # noqa: E402
    BaseLoopySkill,
    LoopySkillRunner,
    SkillEvolutionEngine,
    TextLoopMiner,
    TrajectoryAuditor,
)
from em_cubed.ontology import (  # noqa: E402
    AutomatedTripleMigrationEngine,
    CompetencyQuestion,
    ConceptInductionEngine,
    ConstraintSteeringCompiler,
    DecisionSupportQuestion,
    DerivedPropertyReducer,
    DescriptionLogicExpression,
    EntityType,
    EventType,
    ExactTruthmaker,
    ExactTruthmakerClassifier,
    FederatedOntologyRegistry,
    ForwardBackwardCompatibilityChecker,
    GeoLocation,
    GraphPathRAG,
    HyperintensionalEvaluator,
    InterfaceImplementation,
    KnowledgeElicitationPipeline,
    KnowledgeGraphVisualizer,
    MultiAgentToposConsensus,
    NeuronConceptAligner,
    ObjectBacklinkRegistry,
    OntoCleanPartition,
    OntologicalHealthMonitor,
    OntologyEventStreamProcessor,
    OntologyHealthReport,
    OntologyInterface,
    OntologyLedgerValidator,
    OntologySchemaMigrator,
    OntologyTriple,
    OWLImporter,
    PMESTFacets,
    RDFSerializer,
    ReactiveRule,
    ReducerType,
    SchemaMigrationStep,
    SchemaVersion,
    SelfHealingGuardrailEngine,
    SHACLConstraintGenerator,
    SpatialProximityReasoner,
    StateFragment,
    StreamEvent,
    StreamProcessingResult,
    SubobjectClassifier,
    TemporalSnapshotQueryEngine,
    TemporalSpatialTriple,
    TimeInterval,
    TripleInductionEngine,
    TruthValue,
    WorldStateTimeline,
)
from em_cubed.orchestration.dual_engine_swarm import (  # noqa: E402
    DualEngineSwarmOrchestrator,
    SwarmExecutionReport,
    SwarmRunConfig,
)
from em_cubed.surfaces import OntologyMonad, SurfaceFunctor, SurfaceMorphism  # noqa: E402
