[mypy]
ignore_missing_imports = true
warn_unused_ignores = false

# Stricter settings for the surfaces subpackage — gradually typed.
[mypy-em_cubed.surfaces.*]
strict_optional = true
warn_return_any = false
warn_unused_ignores = false
disallow_untyped_defs = false
